### PR TITLE
Fix weighted power by using proper rolling window

### LINKED ISSUE #658: Stress Scores not matching Trainingpeaks
I noticed that since the most recent release (which required a re-sync of activities), my Power-based stress score does not match TSS calculated by Trainingpeaks.  I have checked that both are using the same FTP and ride data, and yet there is a small (~7.5% difference).  StravastiX reports a lower stress score.

Prior to the release, the numbers were spot on.

Happy to provide data as appropriate...and most importantly, thanks for a great tool.

Bill

### PR DESCRIPTION
**Pull request by aprokop**
Fix #658.

@thomaschampagne This is work in progress. Just wanted to show you what I'm thinking. Btw, is there a way to quickly recalculate the metrics without clearing all activities in the plugin? 

I also have several questions:
1. [Here](https://github.com/thomaschampagne/elevate/blob/12ba302446529c9c53def2a35b19ec967558574b/plugin/core/scripts/processors/activity-computer.ts#L659) Am I right assuming that the delta time between too samples may not be consistent? I.e., it could be of different length between different samples? I assume that that is the case for Garmin watches in Smart mode, for example.
2. What's the right way to treat non-moving samples? Should I just ignore them completely, or continue rolling window through them? If the stopped interval is long, the average will automatically become zero. However, depending on the approach, there will be some differences in averages in the first several samples after stopping. My preference is roll through them.
3. Could you please explain the logic behind [this](	https://github.com/thomaschampagne/elevate/blob/12ba302446529c9c53def2a35b19ec967558574b/plugin/core/scripts/processors/activity-computer.ts#L656) check?
4. In the other issue, you mentioned 60s vs 30s interval. Why was it changed?

### CODE REVIEW

File: plugin/core/scripts/processors/activity-computer.ts [hunk 1]
```diff
@@ -667,20 +668,19 @@ export class ActivityComputer {
 					totalMovingInSeconds += durationInSeconds;
 				}
 
-				timeWindowValue += durationInSeconds; // Add seconds to time buffer
-				sumPowerTimeWindow.push(powerArray[i]); // Add power value
+				rollingSum += powerArray[i];
+				rollingWindowSize += durationInSeconds;
 
-				if (timeWindowValue >= ActivityComputer.AVG_POWER_TIME_WINDOW_SIZE) {
+				sum4thPower += Math.pow(rollingSum/rollingWindowSize, 4);
```
Comment (aprokop) [inline plugin/core/scripts/processors/activity-computer.ts]: Should be: `rollingSum/(i-rolling_index+1)`

**Comment by aprokop** [comment]
Hmm, I'm trying to test locally. Couple tests failed, but I see increased TSS. However, I have trouble testing in the app, as the "Use cycling data power when available" toggle on Fitness Trend page does not seem to do anything.

**Comment by aprokop** [comment]
OK, I have exact matches between Elevate and TP for my trainer rides. This included one two hour ride where I took an hour break in the middle (for this ride, PSS and TSS differ by 1, 95 vs 96). 

So, I think I just need to clean the code and fix the tests. To do that, I need to have a better picture based on the answers to the posted questions.

**Comment by aprokop** [comment]
I think this is ready for review. I still don't understand some checks (like `_.isNumber(velocityArray[i])`), but I don't think this matters. One (controversial) change is getting back to 30s instead of 60s.

**Comment by thomaschampagne** [comment]
@aprokop Thanks for this involved work! I'll dive into review and reply you in details asap ;) Thanks !!!

**Comment by thomaschampagne** [comment]
@aprokop Thanks again for this work. Starting to reply to your questions first

>is there a way to quickly recalculate the metrics without clearing all activities in the plugin?

Unfortunately no, a clear re-sync is required :(

>1. Am I right assuming that the delta time between too samples may not be consistent

You right it can be 1, 2 , 5 sec..

> 2. What's the right way to treat non-moving samples? [...] My preference is roll through them

They should not be ignored. You're right on rolling through them

>3. Could you please explain the logic behind this check?

- If you're ride is flagged as "on trainer" => you want to have power data calculated
- If you're ride is NOT flagged as "on trainer" => you still want to have power data calculated because you provided power data stream. 
-  If you're ride is NOT flagged as "on trainer" and you forgot to disable your GPS (= speed is always 0) => you want to have power data calculated

>4. In the other issue, you mentioned 60s vs 30s interval. Why was it changed?

It was changed/tweaked to have calculated results matching known real results. This matching procedure has been done through unit tests.

> I still don't understand some checks (like _.isNumber(velocityArray[i]))

See previous reply "_If you're ride is NOT flagged as "on trainer" and you forgot to disable your GPS (= speed is always 0) => you want to have power data calculated_"

I will dive and test the code

Thanks again !
